services:
  taskflow-app:
    image: ${FULL_IMAGE}   # Docker Compose récupère la valeur depuis .env
    container_name: taskflow-app
    restart: unless-stopped
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.taskflow-app.rule=Host(`taskflow-app.rickdan.ddns-ip.net`)"
      - "traefik.http.routers.taskflow-app.entrypoints=websecure"
      - "traefik.http.routers.taskflow-app.tls=true"
      - "traefik.http.routers.taskflow-app.tls.certresolver=myresolver"

networks:
  traefik_net:
    external: true
