version: "3.9"

services:
  taskflow-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskflow-app:local
    container_name: taskflow-app
    restart: unless-stopped

    ports:
      - "8080:80"


