name: "Security DAST Scan (OWASP ZAP)"

on:
  workflow_run:
    workflows: ["CI/CD with Docker & Trivy"] # VÃ©rifie que c'est EXACTEMENT le 'name' de ton premier fichier
    types:
      - completed
  workflow_dispatch: # TrÃ¨s utile pour tester sans redÃ©ployer

permissions:
  contents: write
  issues: write
  security-events: write

jobs:
  zap_scan:
    name: DAST Scan with OWASP ZAP
    runs-on: ubuntu-latest
    # Condition : SuccÃ¨s du dÃ©ploiement OU lancement manuel
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Ã‰tape cruciale : On s'assure que le serveur a fini de redÃ©marrer
      - name: Wait for server readiness
        run: sleep 30

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://taskflow-app.rickdan.ddns-ip.net'
          #cmd_options: '-r zap_report.html'
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false # Passe Ã  true quand tu seras prÃªt Ã  bloquer les dÃ©ploiements non sÃ©curisÃ©s

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always() 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: security-reports/${{ github.run_number }}
          keep_files: true
          publish_branch: gh-pages

      - name: Post Summary
        if: always()
        run: |
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/security-reports/${{ github.run_number }}/zap_report.html"
          echo "### ðŸ›¡ï¸ Rapport de SÃ©curitÃ© Dynamique (DAST)" >> $GITHUB_STEP_SUMMARY
          echo "Le scan automatique OWASP ZAP s'est terminÃ©." >> $GITHUB_STEP_SUMMARY
          echo "- **Cible :** https://taskflow-app.rickdan.ddns-ip.net" >> $GITHUB_STEP_SUMMARY
          echo "- **Statut du dÃ©ploiement prÃ©cÃ©dent :** ${{ github.event.workflow_run.conclusion }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "ðŸ”— [Cliquez ici pour voir le rapport HTML complet]($REPORT_URL)" >> $GITHUB_STEP_SUMMARY